language: python
python:
    - "2.7"
    - "3.4"

install:
  - pip install coveralls nose pytest
  - pip install -r requirements.txt
  - python setup.py develop

script:
  # Have to order things this way so setup_travis get's called by the test modules
  - py.test tests --doctest-modules sshutil
