language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
# Until travis fixes https://github.com/travis-ci/travis-ci/issues/4756
# - TOXENV=pypy
# - TOXENV=pypy3

install:
  - pip install tox
  - pip install coveralls
  - pip install nose

script:
  - tox -e $TOXENV
